name: Test builds on multiple OSes

on:
  push:
    branches:
      - v0.x.x

jobs:
  test_mac:
    # runs-on: macOS-latest
    runs-on: macOS-10.14
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true
    - name: Install D and Dub
      run: |
        brew install dmd
        brew install dub
        brew install sqlite3
    - name: Build and test agora
      run: |
        ./ci/travis_osx_setup.sh
        set -xeu
        set -o pipefail
        export PATH="${PATH-}:$HOME/bin/"
        export LIBRARY_PATH="${LD_LIBRARY_PATH-}:/usr/local/lib/"
        export PKG_CONFIG_PATH="/usr/local/opt/sqlite/lib/pkgconfig"
        dub test -b unittest-cov --skip-registry=all --compiler=dmd

  # test_ubuntu:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v1
  #     with:
  #       submodules: true
  #   - name: Install D and Dub
  #     run: |
  #       DMD_VERSION=2.088.0
  #       wget http://downloads.dlang.org/releases/2.x/${DMD_VERSION}/dmd_${DMD_VERSION}-0_amd64.deb
  #       sudo dpkg -i dmd_${DMD_VERSION}-0_amd64.deb
  #       sudo apt install -f
  #       rm -fv dmd_${DMD_VERSION}-0_amd64.deb
  #   - name: Build and test agora
  #     run: |
  #       ./ci/travis_linux_setup.sh
  #       ./ci/run.sh
