name: Build & Test Agora
on: [push, pull_request]

jobs:
    mac_build:
        name: Build & Run test-suite on Mac
        strategy:
            matrix:
                os: [macOS-10.14]
                dc: [dmd-2.088.0, dmd-2.087.1, ldc-1.17.0, ldc-1.16.0, dmd-master, ldc-master]

        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/checkout@v1

            - name: Prepare environment
              uses: mihails-strasuns/setup-dlang@v0.3.0
              with:
                  compiler: ${{ matrix.dc }}
              run: |
                brew install sqlite3
                ./ci/travis_osx_setup.sh

            - name: Run test-suite & build Agora
              run: |
                set -xeu
                set -o pipefail
                export PATH="${PATH-}:$HOME/bin/"
                export LIBRARY_PATH="${LD_LIBRARY_PATH-}:/usr/local/lib/"
                export PKG_CONFIG_PATH="/usr/local/opt/sqlite/lib/pkgconfig"
                ./ci/run.sh

    linux_build:
        name: Build & Run test-suite on Linux
        strategy:
            matrix:
                os: [ubuntu-latest]
                dc: [dmd-2.088.0, dmd-2.087.1, ldc-1.17.0, ldc-1.16.0, dmd-master, ldc-master]

        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/checkout@v1

            - name: Prepare environment
              uses: mihails-strasuns/setup-dlang@v0.3.0
              with:
                  compiler: ${{ matrix.dc }}
              run: |
                brew install sqlite3
                ./ci/travis_linux_setup.sh

            - name: Run test-suite & build Agora
              run: |
                set -xeu
                set -o pipefail
                export PATH="${PATH-}:$HOME/bin/"
                export LIBRARY_PATH="${LD_LIBRARY_PATH-}:/usr/local/lib/"
                export PKG_CONFIG_PATH="/usr/local/opt/sqlite/lib/pkgconfig"
                ./ci/run.sh
