name: Build & Test Agora
on: [push, pull_request]

jobs:
    mac_build:
        name: Build & Run test-suite on Mac OS
        strategy:
            matrix:
                os: [macOS-10.14]
                # dc: [dmd-2.088.0, dmd-2.087.1, ldc-1.17.0, ldc-1.16.0, dmd-master, ldc-master]
                dc: [dmd-2.087.1]

        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/checkout@v1
              with:
                submodules: true
            - name: Prepare compiler
              uses: mihails-strasuns/setup-dlang@v0.3.0
              with:
                  compiler: ${{ matrix.dc }}
            - name: Run test-suite & build Agora
              run: |
                ./ci/github_mac_setup.sh
                ./ci/run.sh

    # linux_build:
    #     name: Build & Run test-suite on Linux
    #     strategy:
    #         matrix:
    #             os: [ubuntu-latest]
    #             # dc: [dmd-2.088.0, dmd-2.087.1, ldc-1.17.0, ldc-1.16.0, dmd-master, ldc-master]
    #             dc: [dmd-2.087.1]

    #     runs-on: ${{ matrix.os }}
    #     steps:
    #         - uses: actions/checkout@v1
    #           with:
    #             submodules: true
    #         - name: Prepare compiler
    #           uses: mihails-strasuns/setup-dlang@v0.3.0
    #           with:
    #               compiler: ${{ matrix.dc }}
    #         - name: Run test-suite & build Agora
    #           run: |
    #             ./ci/github_linux_setup.sh
    #             ./ci/run.sh
